export interface Vec2 {
  x: number;
  y: number;
}

export type TileKind = 'ground';

export interface World {
  width: number;
  height: number;
  tiles: TileKind[][]; // [y][x] — kept for the renderer/pathfinding, everything is walkable
}

export type MemoryKind = 'move' | 'said' | 'heard' | 'thought' | 'made' | 'noticed' | 'system';

export interface MemoryEvent {
  id: string;
  tick: number;
  kind: MemoryKind;
  text: string;
}

export type Direction = 'north' | 'south' | 'east' | 'west' | 'random';

export type AgentIntent =
  | { kind: 'move'; direction: Direction }
  | { kind: 'talk_to'; targetId: string }
  | { kind: 'say'; message: string }
  | { kind: 'create'; content: string }
  | { kind: 'wait' };

/** Something an agent left behind — its meaning is whatever the agent said it is; the engine never interprets it. */
export interface WorldObject {
  id: string;
  creatorId: string;
  creatorLabel: string;
  pos: Vec2;
  content: string;
  tick: number;
}

/** What an agent should do once a `walking` path finishes. */
export type WalkGoal = { kind: 'wander' } | { kind: 'talk'; targetId: string };

export type ActivityState =
  | { kind: 'idle'; cooldownUntilTick: number }
  | { kind: 'thinking' } // waiting on a decision LLM call
  | { kind: 'walking'; then: WalkGoal }
  | { kind: 'talking'; withAgentId: string }; // a multi-turn conversation is in flight

export interface SpeechBubble {
  text: string;
  expiresAtTick: number;
}

export interface Agent {
  id: string;
  label: string;
  /** The Ollama model this specific agent's decisions and speech are generated by. */
  model: string;
  color: string;
  pos: Vec2; // current tile position (integer)
  path: Vec2[]; // remaining tiles to walk, next-first
  activity: ActivityState;
  memory: MemoryEvent[];
  speech: SpeechBubble | null;
}

export interface LogEntry {
  id: string;
  tick: number;
  text: string;
  kind: 'conversation' | 'creation' | 'system';
  speakerLabel?: string;
}

export interface SimClock {
  tick: number;
  running: boolean;
  ticksPerSecond: number; // playback speed
}
