export interface Vec2 {
  x: number;
  y: number;
}

export type TileKind = 'ground';

export interface World {
  width: number;
  height: number;
  tiles: TileKind[][]; // [y][x] — kept for the renderer/pathfinding, everything is walkable
}

/** A fixed place on the map — always known to every agent, not something discovered. */
export type ZoneKind = 'house' | 'shop' | 'restaurant' | 'park';

export interface Zone {
  id: string;
  kind: ZoneKind;
  name: string;
  bounds: { x: number; y: number; w: number; h: number }; // tile-space rectangle
  /** Houses can be bought — the owner is the only one who can rest here. Unowned houses (and
   *  every non-house zone, which never has an owner) are open to anyone. */
  ownerId: string | null;
  ownerLabel: string | null;
}

export type MemoryKind =
  | 'said'
  | 'heard'
  | 'thought'
  | 'system'
  | 'job' // took a role/title somewhere
  | 'worked' // earned money at a job
  | 'need' // satisfied hunger/energy/fun
  | 'bought' // spent money on food
  | 'relationship' // how it feels about another agent changed
  | 'reflection' // a higher-level takeaway synthesized from raw memory, not a single event
  | 'gave'; // money changed hands with another agent

export interface MemoryEvent {
  id: string;
  tick: number;
  kind: MemoryKind;
  text: string;
}

export type Direction = 'north' | 'south' | 'east' | 'west' | 'random';

export type AgentIntent =
  | { kind: 'move'; direction: Direction }
  | { kind: 'go_to'; targetId: string }
  | { kind: 'talk_to'; targetId: string }
  | { kind: 'say'; message: string }
  | { kind: 'satisfy_need'; need: 'energy' | 'fun' }
  | { kind: 'buy_food' }
  | { kind: 'buy_house' }
  | { kind: 'give_money'; targetId: string; amount: number }
  | { kind: 'take_job'; title: string }
  | { kind: 'work' }
  | { kind: 'wait' };

/** A role or job title an agent has claimed for itself at a specific zone — entirely
 *  self-declared, in its own words; nothing stops two agents from claiming the same one. */
export interface AgentRole {
  zoneId: string;
  title: string;
  tick: number;
}

/** One agent's own view of another — asymmetric on purpose (A can consider B a
 *  friend without B feeling the same), and updated by the agent's own model, not
 *  a fixed ladder the engine imposes. */
export interface Relationship {
  otherId: string;
  otherLabel: string;
  affinity: number; // -100..100
  label: string; // free text, in the agent's own words
  updatedTick: number;
}

export interface Needs {
  hunger: number; // 0..100, 100 = fully satisfied
  energy: number;
  social: number;
  fun: number;
}

/** What an agent should do once a `walking` path finishes. */
export type WalkGoal = { kind: 'wander' } | { kind: 'talk'; targetId: string };

export type ActivityState =
  | { kind: 'idle'; cooldownUntilTick: number }
  | { kind: 'thinking' } // waiting on a decision LLM call
  | { kind: 'walking'; then: WalkGoal }
  | { kind: 'talking'; conversationId: string }; // in a multi-turn conversation — could be 2+ people

export interface SpeechBubble {
  text: string;
  expiresAtTick: number;
}

export interface Agent {
  id: string;
  label: string;
  /** The Ollama model this specific agent's decisions and speech are generated by. */
  model: string;
  color: string;
  pos: Vec2; // current tile position (integer)
  path: Vec2[]; // remaining tiles to walk, next-first
  activity: ActivityState;
  memory: MemoryEvent[];
  /** Higher-level takeaways the agent's own model periodically synthesizes from its raw memory
   *  ("I've talked to B three times, we get along") — separate from the raw event-by-event
   *  stream so it survives being crowded out by recency and actually informs later decisions. */
  reflections: MemoryEvent[];
  lastReflectionTick: number;
  speech: SpeechBubble | null;
  needs: Needs;
  wallet: number;
  roles: AgentRole[];
  relationships: Record<string, Relationship>; // keyed by other agent's id
}

export interface LogEntry {
  id: string;
  tick: number;
  text: string;
  kind: 'conversation' | 'event' | 'system';
  speakerLabel?: string;
  /** Who this was said to, if anyone in particular (omitted for broadcast "say"). */
  listenerLabel?: string;
}

export interface SimClock {
  tick: number;
  running: boolean;
  ticksPerSecond: number; // playback speed
}

export interface ConversationLine {
  speakerLabel: string;
  text: string;
  tick: number;
}

/** A conversation currently in flight, tracked separately from the flat transcript so
 * simultaneous conversations (normal with several agents around) stay visually separable.
 * Two or more participants — anyone nearby can walk up and join an ongoing one. */
export interface ActiveConversation {
  id: string;
  participantIds: string[];
  participantLabels: string[];
  lines: ConversationLine[];
  startedTick: number;
}

/** Cumulative, per-model — not per-agent, since two agents can share a model and the whole
 *  point is comparing models against each other. Tagged with whatever model an agent was
 *  actually running at the moment each event happened, so reassigning models mid-run doesn't
 *  retroactively misattribute earlier history. */
export interface ModelStats {
  model: string;
  actionCounts: Record<string, number>;
  messagesSpoken: number;
  moneyEarned: number;
  moneySpent: number;
  moneyGiven: number;
  moneyReceived: number;
}

/** One point in a relationship's affinity-over-time history, recorded whenever it actually
 *  changes (not sampled on a timer) — enough to draw a trend line without polling. */
export interface AffinityPoint {
  tick: number;
  agentId: string;
  agentLabel: string;
  otherId: string;
  otherLabel: string;
  affinity: number;
}
